#!/usr/bin/env python3
"""AUTO-GENERATED helper: emit a per-module function/class signature map (Markdown).
Usage: python3 gen-fnmap.py <package_dir>  > generated/20-module-function-map.md
Static AST only — does not import the target package."""
import ast, sys, pathlib

root = pathlib.Path(sys.argv[1])
out = ["# Module -> function / class map", "",
       "_AUTO-GENERATED by gen.sh (gen-fnmap.py) — do not edit; regenerate._", ""]


def sig(fn: ast.AST) -> str:
    a = fn.args
    parts = [ar.arg for ar in a.posonlyargs] + [ar.arg for ar in a.args]
    if a.vararg:
        parts.append("*" + a.vararg.arg)
    if a.kwonlyargs and not a.vararg:
        parts.append("*")
    parts += [ar.arg for ar in a.kwonlyargs]
    if a.kwarg:
        parts.append("**" + a.kwarg.arg)
    ret = ""
    try:
        if fn.returns is not None:
            ret = " -> " + ast.unparse(fn.returns)
    except Exception:
        ret = ""
    return f"{fn.name}({', '.join(parts)}){ret}"


for p in sorted(root.glob("*.py")):
    if p.name == "__init__.py":
        continue
    try:
        tree = ast.parse(p.read_text())
    except Exception as e:  # noqa: BLE001
        out.append(f"## `{p.name}`\n_parse error: {e}_\n")
        continue
    funcs = [n for n in tree.body if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef))]
    classes = [n for n in tree.body if isinstance(n, ast.ClassDef)]
    out.append(f"## `{p.name}`  ({len(funcs)} functions, {len(classes)} classes)")
    for c in classes:
        meths = [m for m in c.body if isinstance(m, (ast.FunctionDef, ast.AsyncFunctionDef))]
        out.append(f"- **class {c.name}** — methods: " + (", ".join(m.name for m in meths) or "(none)"))
    if funcs:
        out.append("")
        for f in funcs:
            out.append(f"- `{sig(f)}`")
    out.append("")

print("\n".join(out))
